version: '3'
services:

  ktorapp:
    build: .
    container_name: bookstore
    ports:
      - "8080:8080"
    depends_on:
      - mongotest
    restart: always
    networks:
      - bookstore-network

  mongotest:
    image: mongo:latest
    container_name: mongotest
    ports:
      - "27017:27017"
    networks:
        - bookstore-network
#    volumes:
#      - ./data:/data/db
#    networks:
#      - mynetwork
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#    restart: always

  postgres:
   image: postgres
   container_name: bookstore_db
   restart: always
   environment:
     POSTGRES_PASSWORD: password123
     POSTGRES_USER: bookstore
     POSTGRES_DB: bookstore
   volumes:
    - bookstore-db-data:/var/lib/postgresql/data
   ports:
    - "5432:5432"
   networks:
    - bookstore-network

networks:
  bookstore-network:

volumes:
  bookstore-db-data:
